// @vitest-environment jsdom
import { describe, expect, it } from 'vitest';
import {
  MAX_TRANSFORM_EXCERPT_LENGTH,
  documentExtension,
  transformSyntaxForExtension,
} from '@hvault/shared';
import { runTransform } from '../../src/sandbox/transform/formatEngine';
import {
  decodeTransformSource,
  transformReplySchema,
} from '../../src/services/documents/transform';
import {
  FORMAT_CORPUS,
  FORMAT_CORPUS_FILES,
  TRANSFORM_COMBINATIONS,
  flagsOf,
  readFormatCorpus,
  type FormatCorpusEntry,
  type TransformCombination,
} from './format-corpus';

/**
 * The format-and-repair engine, driven with hostile documents.
 *
 * ## The contract, in four clauses
 *
 * For EVERY corpus entry and EVERY combination of the two transforms a user can
 * tick:
 *
 *   1. the engine RESOLVES — it never throws, because a rejection reaches the
 *      panel as a spinner that never stops rather than as a reason;
 *   2. what it resolves with PARSES under the host's own reply schema, which is
 *      what the application will actually validate the message against. An
 *      engine output the schema rejects is a transform that dies at the message
 *      boundary for every user, with nothing in the engine having failed;
 *   3. a SUCCESS is really a success — repaired JSON parses, a formatted
 *      document formats to itself, and a JSON Lines record never spans lines;
 *   4. a FAILURE is describable — a positive line and column or an honest
 *      `null`, and an excerpt inside its bound.
 *
 * And it never HANGS: the leg deadline in `scripts/ci/fuzz-gate.mjs` is what
 * enforces that, because a wedged parser is precisely the failure a test
 * framework reports worst.
 *
 * ## Why a corpus rather than generated bytes
 *
 * Random bytes are almost never a document. The inputs that break a formatter
 * are the ones a real editor, a real download and a real half-finished save
 * produce: a trailing comma, a file cut off mid-array, a Windows byte-order
 * mark, two documents concatenated by a script that forgot a newline. Each is
 * committed, named, and explained in `format-corpus.ts`.
 */

/** The entries whose bytes reach a parser at all. */
const DECODABLE = FORMAT_CORPUS.filter((entry) => entry.refusedByDecoder !== true);

/** Every (entry, combination) pair, which is the whole matrix the suites run. */
const MATRIX = DECODABLE.flatMap((entry) =>
  TRANSFORM_COMBINATIONS.map(
    (combination) => [`${entry.file} ${combination}`, entry, combination] as const,
  ),
);

function decodedText(entry: FormatCorpusEntry): string | null {
  const decoded = decodeTransformSource(readFormatCorpus(entry.file));
  return 'refusal' in decoded ? null : decoded.text;
}

describe('the corpus and its index agree, in both directions', () => {
  it('lists every file on disk, and every listed file exists', () => {
    // A file dropped into the directory and never listed is run by NOTHING, and
    // the reason it was added is lost. That direction is the silent one, which
    // is why both are asserted.
    expect([...FORMAT_CORPUS_FILES].sort()).toEqual(
      [...FORMAT_CORPUS.map((entry) => entry.file)].sort(),
    );
    expect(FORMAT_CORPUS.length).toBeGreaterThan(10);
  });

  it('gives every entry a reason a reviewer can read', () => {
    for (const entry of FORMAT_CORPUS) {
      expect(entry.why.length, entry.file).toBeGreaterThan(40);
    }
  });

  it('names an extension the panel would actually offer a transform for', () => {
    for (const entry of FORMAT_CORPUS) {
      expect(transformSyntaxForExtension(documentExtension(entry.file)), entry.file).not.toBeNull();
    }
  });
});

describe('the decoder refuses exactly the entries that are not plain UTF-8', () => {
  it.each(FORMAT_CORPUS.map((entry) => [entry.file, entry] as const))('%s', (file, entry) => {
    const decoded = decodeTransformSource(readFormatCorpus(entry.file));
    if (entry.refusedByDecoder === true) {
      expect(decoded, file).toHaveProperty('refusal');
      if (!('refusal' in decoded)) return;
      // A refusal a user can act on, not a category error.
      expect(decoded.refusal).toContain('uploaded exactly as it is');
      return;
    }
    expect(decoded, file).toHaveProperty('text');
  });
});

describe('every corpus entry, under every combination of transforms', () => {
  it.each(MATRIX)(
    '%s',
    async (label, entry, combination: TransformCombination) => {
      const text = decodedText(entry);
      expect(text, label).not.toBeNull();
      if (text === null) return;
      const ext = documentExtension(entry.file);
      const syntax = transformSyntaxForExtension(ext);
      const flags = flagsOf(combination);

      // CLAUSE 1: it resolves. `runTransform` is awaited without a `catch`, so a
      // rejection fails this test rather than becoming an unhandled rejection.
      const result = await runTransform({ text, ext, ...flags });

      // CLAUSE 2: the host's own schema accepts it.
      const parsed = transformReplySchema.safeParse(result);
      expect(parsed.success, `${label}: ${JSON.stringify(parsed.error?.issues ?? [])}`).toBe(true);

      // The truth table, in BOTH directions. "It failed" is what a broken engine
      // reports for everything, so an entry expected to fail is listed rather
      // than inferred — and an entry expected to SUCCEED that quietly stopped is
      // the regression nobody would otherwise notice.
      const mustFail = (entry.failing ?? []).includes(combination);
      expect(
        result.kind,
        `${label}: ${result.kind === 'transformFailed' ? result.message : ''}`,
      ).toBe(mustFail ? 'transformFailed' : 'transformed');

      if (result.kind === 'transformFailed') {
        // CLAUSE 4: a failure is describable.
        expect(result.message.length, label).toBeGreaterThan(0);
        if (result.line !== null) expect(result.line, label).toBeGreaterThan(0);
        if (result.column !== null) {
          expect(result.column, label).toBeGreaterThan(0);
          // A column without a line is unplaceable.
          expect(result.line, label).not.toBeNull();
        }
        expect(result.excerpt.length, label).toBeLessThanOrEqual(MAX_TRANSFORM_EXCERPT_LENGTH);
        // And nothing half-transformed escapes with it.
        expect(result, label).not.toHaveProperty('text');
        return;
      }

      // CLAUSE 3: a success is really a success.
      expect(result.formatted, label).toBe(flags.format);
      expect(result.repaired, label).toBe(flags.repair);
      expect(result.tool.length, label).toBeGreaterThan(0);
      expect(result.toolVersion.length, label).toBeGreaterThan(0);

      if (combination === 'repair' && syntax === 'json') {
        // The repairer's whole promise: what comes out is STRICT JSON. Only
        // asserted for a repair that ran alone — a `.jsonc` or `.json5` file
        // formatted afterwards is legitimately printed back in its own dialect,
        // trailing comma and all, because the extension is what declares it.
        expect(() => JSON.parse(result.text) as unknown, label).not.toThrow();
      }
      if (syntax === 'jsonl') {
        // A record may never be split across lines, whichever transform ran: the
        // format is defined line by line, so one broken record silently becomes
        // several invalid ones.
        for (const line of result.text.split('\n')) {
          const record = line.endsWith('\r') ? line.slice(0, -1) : line;
          if (record.trim() === '') continue;
          expect(() => JSON.parse(record) as unknown, `${label}: ${record}`).not.toThrow();
        }
      }
      if (text.includes('\r\n')) {
        // A CRLF document comes back a CRLF document. Prettier's default rewrites
        // them, which would read as a change to every line of the file.
        expect(result.text, label).toContain('\r\n');
        expect(result.text.split('\n').length, label).toBe(text.split('\n').length);
      }
    },
    30_000,
  );
});

describe('formatting is idempotent over the whole corpus', () => {
  const cases = DECODABLE.filter((entry) => !(entry.failing ?? []).includes('format')).map(
    (entry) => [entry.file, entry] as const,
  );

  it.each(cases)(
    '%s',
    async (file, entry) => {
      // `format(format(x)) === format(x)` is the property that makes a formatter
      // safe to run twice — and a user who re-uploads a document they already
      // formatted must see "nothing changed" rather than a second rewrite.
      const text = decodedText(entry);
      expect(text, file).not.toBeNull();
      if (text === null) return;
      const ext = documentExtension(file);
      const once = await runTransform({ text, ext, format: true, repair: false });
      expect(once.kind, file).toBe('transformed');
      if (once.kind !== 'transformed') return;
      const twice = await runTransform({ text: once.text, ext, format: true, repair: false });
      expect(twice.kind, file).toBe('transformed');
      if (twice.kind !== 'transformed') return;
      expect(twice.text, file).toBe(once.text);
    },
    30_000,
  );

  it('covers most of the corpus, so the property is not being asserted over two files', () => {
    expect(cases.length).toBeGreaterThan(10);
  });
});

describe('repairing twice is a no-op, so a re-upload is not a fresh rewrite', () => {
  const cases = DECODABLE.filter((entry) => !(entry.failing ?? []).includes('repair')).map(
    (entry) => [entry.file, entry] as const,
  );

  it.each(cases)(
    '%s',
    async (file, entry) => {
      const text = decodedText(entry);
      if (text === null) return;
      const ext = documentExtension(file);
      const repaired = await runTransform({ text, ext, format: false, repair: true });
      expect(repaired.kind, file).toBe('transformed');
      if (repaired.kind !== 'transformed') return;
      // The second pass is handed strict JSON, which `jsonrepair` returns
      // byte-identical. A repairer that kept changing its own output would make
      // every re-upload a fresh rewrite to confirm.
      const again = await runTransform({ text: repaired.text, ext, format: false, repair: true });
      expect(again.kind, file).toBe('transformed');
      if (again.kind !== 'transformed') return;
      expect(again.text, file).toBe(repaired.text);
    },
    30_000,
  );
});

describe('a JSON Lines record too long to stay on one line is refused, not corrupted', () => {
  it('names the line rather than writing a record the formatter broke apart', async () => {
    // GENERATED rather than committed: at roughly a megabyte this would be the
    // largest file in the repository and no reviewer could read it, and the
    // construction is exact. Measured against Prettier 3.9.5, a record of about
    // this size is where its filling printer stops keeping a numeric array flat
    // even at the width the engine asks for.
    const record = `[${Array.from({ length: 150_000 }, (_, index) => String(index)).join(',')}]`;
    expect(record.length).toBeGreaterThan(900_000);
    const result = await runTransform({
      text: `{"ok":1}\n${record}\n`,
      ext: 'jsonl',
      format: true,
      repair: false,
    });
    expect(result.kind).toBe('transformFailed');
    if (result.kind !== 'transformFailed') return;
    expect(result.stage).toBe('format');
    expect(result.line).toBe(2);
    expect(result.message).toContain('may not be split across lines');
    // The alternative — writing it out anyway — turns one valid record into
    // several invalid ones, silently, in a format defined line by line.
    expect(transformReplySchema.safeParse(result).success).toBe(true);
  }, 60_000);
});
