import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootPkg = JSON.parse(
  readFileSync(resolve(__dirname, '..', '..', '..', 'package.json'), 'utf-8'),
);

const version = rootPkg.version;
const outFile = resolve(__dirname, '..', 'src', 'generated', 'version.ts');

// `src/generated/` is gitignored, so on a fresh clone it does not exist and
// writeFileSync would throw ENOENT — breaking `npm run build:shared`, which is
// the first command a new contributor runs and a prerequisite of every other
// build. It only ever worked in a working tree where a previous build had
// already created the directory.
mkdirSync(dirname(outFile), { recursive: true });

const safeVersion = JSON.stringify(version);
writeFileSync(
  outFile,
  `// Auto-generated by scripts/inject-version.js — do not edit\nexport const APP_VERSION = ${safeVersion};\n`,
);
